# Minimal makefile for MkDocs documentation

# You can set these variables from the command line.
MKDOCS := mkdocs
DOCS_DIR := docs
SITE_DIR := site

# Put it first so that "make" without argument is like "make help".
help:
	@echo "Usage: make [command]"
	@echo ""
	@echo "Available commands:"
	@echo "  help      Show this help message"
	@echo "  build     Build the MkDocs documentation"
	@echo "  serve     Serve the MkDocs documentation locally"
	@echo "  deploy    Deploy the MkDocs documentation (e.g., to GitHub Pages)"
	@echo "  clean     Remove the generated site directory"

.PHONY: help build serve deploy clean

build:
	@$(MKDOCS) build --config-file $(DOCS_DIR)/mkdocs.yml --site-dir $(SITE_DIR)

serve:
	@$(MKDOCS) serve --config-file $(DOCS_DIR)/mkdocs.yml

deploy:
	@$(MKDOCS) gh-deploy --config-file $(DOCS_DIR)/mkdocs.yml --site-dir $(SITE_DIR)

clean:
	@rm -rf $(SITE_DIR)
