site_name: EasyTest
nav:
    - Home: index.md
    - API Reference: api_reference.md
    - Changelog: changelog.md
    - Code of Conduct: conduct.md
    - Contributing: contributing.md
    - Requirements: requirements.md
theme: mkdocs
docs_dir: docs
use_directory_urls: false