site_name: EasyTest
nav:
    - Home: index.md
    - Documentation: notebook.md
    - API Reference: api_reference.md
    - Changelog: changelog.md
    - Code of Conduct: conduct.md
    - Contributing: contributing.md
    - Requirements: requirements.md
theme:
  name: material
  features:
    - toc.integrate 
docs_dir: docs
use_directory_urls: false


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true